### ISSUE TITLE
BIP 49

### ISSUE THREAD

**Issue by juscamarena** [chainside/btcpy#1]
Would be cool to have BIP 49, address generation from an xpub.

Or at the very least be flexible enough to derive a path.

I do something similar for bitcoinjs-lib here: https://gist.github.com/juscamarena/8b3928599f4c9658a39cf30f632eea95

**Comment by juscamarena** [comment]
BIP49*

**Comment by SimoneBronzini** [comment]
Thanks for your feedback! Management of HD structures is in the TODO list and will be implemented as soon as possible.

**Comment by SimoneBronzini** [comment]
> Or at the very least be flexible enough to derive a path.

The closing commit adds HD derivation functionalities, we plan to also add a higher layer where addresses can be generated for predefined BIPs but this is in the TODO list and will be done eventually
