### ISSUE TITLE
Support for altcoins

### ISSUE THREAD

**Issue by oskyk** [chainside/btcpy#16]
Support for dash and litecoin it is probably just changing a few constants

**Comment by peerchemist** [comment]
There is a branch here with Peercoin support: https://github.com/PeerAssets/btcpy/tree/ppc

However this has to be done differently. I imagine it as passing dict of parameters to setup function.

**Comment by SimoneBronzini** [comment]
I don't think this should be a general purpose altcoin library. I believe a better approach would be the same @peerchemist is using: everyone who wants to develop an altcoin version of this library can fork it and work on it. This prevents the problem of having to update btcpy with new and possibly heavy changes as soon as any altcoin deploys a new feature. In that case, that altcoin's fork can be updated leaving the code for the other coins unchanged.

**Comment by l0rb** [comment]
Maybe the pull could be modified so that it would support just btc but making it easier to add other coins.

**Comment by SimoneBronzini** [comment]
That would be welcome!

**Comment by windxz** [comment]
More and more often I see some weird mining projects. Something`s kept as a secret, concealed. I'm not one of those ppl who not gonna pay attention to it. And here on the forum I saw a link bout the partnership of RUSAL and MiningNow: http://www.coinfox.info/news/8299-russian-aluminum-producer-announces-the-launch-of-a-mining-enterprise. Studied the project http://miningnow.online/ru/, 
all information is available, everything is open! The project was pleasantly surprisin, gonna invest.
