### ISSUE TITLE
Use RFC6979 for signing

### ISSUE THREAD

**Issue by 1504532034** [chainside/btcpy#2]
`ecdsa` supports making deterministic signatures with RFC6979 with `sign_digest_deterministic()`, which should be a drop in replacement.

**Comment by SimoneBronzini** [comment]
Thanks for your feedback! Added the option to deterministically sign that defaults to `True` in commit [3f556641923d3825fca0b082f79b2e87f02dbddb](https://github.com/chainside/btcpy/commit/3f556641923d3825fca0b082f79b2e87f02dbddb). Closing this issue.
