### ISSUE TITLE
Maybe the default version of segwit addresses should be zero

### ISSUE THREAD

**Issue by bilthon** [chainside/btcpy#35]
If I do:

```python
>>> pubKey = PublicKey.unhexlify('034486893a383d2b5d6c1c2ea72b918f5ce3b14b1737ecd987faffa1a4f954a797')
>>> str(pubKey.to_segwit_address())
```
This gives me:
```python
'bc1pna5zac9rgecdktqfs920me8x6ys7ad5fsdw3dh'
```

Which is not the address I'm looking for. If I however explicitly specify the segwit program version:

```python
>>> str(pubKey.to_segwit_address(0))
```

I finally get:

```python
'bc1qna5zac9rgecdktqfs920me8x6ys7ad5fmne6qu'
```

It would be easy to submit a PR with this change, but I'm new to this library and don't know if this would break things or go somewhat against the desired behavior. I'm just saying that, as a user, at this point I expect the version to be zero by default.

**Comment by SimoneBronzini** [comment]
Hello, thanks for reporting this! Which version of `btcpy` are you using? In the current version `pubKey.to_segwit_address()` without parameters would not work, as it is declared as
```python
def to_segwit_address(self, version, mainnet=None):
```
