### ISSUE TITLE
Hello, I am having the following issues to install. 

### ISSUE THREAD

**Issue by leonhatori** [chainside/btcpy#6]
C:\Users\Leon Hatori>pip install chainside-btcpy
Collecting chainside-btcpy
C:\Python27\lib\site-packages\pip-9.0.1-py2.7.egg\pip\_vendor\requests\packages\urllib3\util\ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
C:\Python27\lib\site-packages\pip-9.0.1-py2.7.egg\pip\_vendor\requests\packages\urllib3\util\ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement chainside-btcpy (from versions: )
No matching distribution found for chainside-btcpy

**Comment by SimoneBronzini** [comment]
Looks like you are trying to install this package for python2.7. This package is only available for python3.
